-- IF  EXISTS (SELECT * FROM sys.server_principals WHERE name = N'EcmDbUser')
--    DROP LOGIN [EcmDbUser]
-- GO

RESTORE DATABASE %DATABASE_NAME% FROM DISK = '%DATABASE_BACKUPFILE%' WITH REPLACE, MOVE '%DATABASE_LOGICALNAME_DATA%' TO '%DATABASE_BACKUPFILE%_data.mdf', MOVE '%DATABASE_LOGICALNAME_LOG%' TO '%DATABASE_BACKUPFILE%_log.ldf'
GO

--CREATE LOGIN 'EcmDbUser WITH PASSWORD=N''EcmDbUser', DEFAULT_DATABASE=VizSystem, DEFAULT_LANGUAGE=[us_english]
--GO

-- USE VizECM93
-- CREATE USER [EcmDbUser] FOR LOGIN [EcmDbUser] WITH DEFAULT_SCHEMA=[dbo]
-- EXEC sp_addrolemember 'db_owner', 'EcmDbUser'
-- GO